### ISSUE TITLE
How I can configure  CONFIG_OPT_IDLE and  CONFIG_IDLE_CB_ALT

### ISSUE THREAD

**Issue by mrdsn3** [pstolarz/CoopThreads#1]
I copy your code and get this error how I can solve it 
can you help me plz?

**Comment by pstolarz** [comment]
By editing `src/coop_config.h`.

**Comment by mrdsn3** [comment]
[new 5.txt](https://github.com/pstolarz/CoopThreads/files/6422869/new.5.txt)
 I edit it and get this error   did you knew what s wrong?
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by pstolarz** [comment]
I'm afraid I can't help you with this. I don't know your building toolset, if it is Arduino environment or not, what  source code do you compile, what type of error do you get etc. It looks like simple compilation issue which should be quickly solved by some experienced user, so maybe ask someone to help you with this directly. BTW the file you sent is simply wrong and wont compile.

**Comment by pstolarz** [comment]
I'm afraid I can't help you with this. I don't know your building toolset, if it is Arduino environment or not, what source code do you compile, what type of error do you get etc. It looks like simple compilation issue which should be quickly solved by some experienced user, so maybe ask someone to help you with this directly. BTW The file you sent is strange, why do you uncommented `CONFIG_DBG_LOG_CB_ALT` in-line doc?

EDIT: I was able to compile `CoopIdle` example for NodeMCU 1.0 via Arduino IDE 1.8.13 w/o any problems. Simply uncommended `#define CONFIG_IDLE_CB_ALT` in `src/coop_config.h` and compilation successes.
